name: pokemon_api
description: "Eine Flutter-App, die die Pokemon API verwendet"
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets müssen deklariert werden
  assets:
    - assets/pokeball.png
    - assets/

# Native Splash Screen Konfiguration
flutter_native_splash:
  color: "#FF0000"
  image: assets/pokeball.png
  android: true
  ios: true
  web: true

# App Icon Konfiguration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pokeball.png"
  adaptive_icon_background: "#FF0000"
  adaptive_icon_foreground: "assets/pokeball.png"
