name: pokemon_api
description: "Eine Flutter-App, die die Pokemon API verwendet"
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: "^0.13.1"

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FF0000" # Hintergrundfarbe Rot (Pokémon-Stil)
  image: assets/pokeball.png # dein Pokéball-Icon als Splash-Bild
  android: true
  ios: true
  web: true

flutter_launcher_icons:
android: true
ios: true
image_path: "assets/pokeball.png"
adaptive_icon_background: "#FF0000"
adaptive_icon_foreground: "assets/pokeball.png"
